### ISSUE TITLE
redhad ldaps not working properly

### ISSUE THREAD

**Issue by escube** [bennojoy/openldap_server#14]
There is a task that copies ldap file when ldaps is enabled. 
copy: src=ldap dest=/etc/sysconfig/ldap mode=0755

**Comment by ozbillwang** [comment]
A temp fix in `tasks/configure_ldap.yml`

```
- name: copy the supporting files
  copy: src=ldap dest=/etc/sysconfig/ldap mode=0755
  copy: src=slapd_fedora dest=/etc/sysconfig/slapd mode=0755
  when: openldap_server_enable_ssl and ansible_os_family == 'RedHat'
  notify:
   - restart slapd
```
